<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>komunikat_bledu</name>
   <tag></tag>
   <elementGuidId>9b4f9ff7-5c88-4703-a8f6-ca3756496cfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[id=&quot;statuteAccepted-error&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
