<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zaloz_konto</name>
   <tag></tag>
   <elementGuidId>da2979d0-de73-4aad-b3e2-b8861b31da99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href=&quot;/account-login.bhtml&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
