<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zaloz_nowe_konto</name>
   <tag></tag>
   <elementGuidId>6e9a2647-32d8-4ae8-9330-699eafe5d18f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[class=&quot;cta__label&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
